Repository team-B-free/B-room, pull requests merged in 2022-07, with the labels that each got.

#8 [Feat]#4 - 공지사항 기능 구현
  src/controllers/companyNotice/companyNotice.controller.ts
  src/controllers/index.ts
  src/entities/CompanyNotice.ts
  src/interfaces/companyNotice/ICompanyNotice.ts
  src/routes/companyNotice/companyNotice.route.ts
  src/routes/index.ts
  src/services/companyNotice/companyNotice.service.ts
Labels: ✨ Feature

#16 [Chore] #15 - 채팅 관련 모델링 설정
  package-lock.json
  src/entities/CompanyChat.ts
  src/entities/CompanyChatRoom.ts
  src/entities/User.ts
  src/entities/UserCompanyChat.ts
Labels: ⚙ Setting

#19 [Feat]#14 - 공지사항 서비스 구현
  package-lock.json
  src/controllers/companyNotice/companyNotice.controller.ts
  src/controllers/test.controller.ts
  src/entities/CompanyNotice.ts
  src/entities/User.ts
  src/middlewares/auth.middlewares.ts
  src/modules/message.ts
  src/modules/role.ts
  src/routes/companyNotice/companyNotice.route.ts
  src/routes/index.ts
  src/routes/test.route.ts
  src/services/companyNotice/companyNotice.service.ts
  src/services/index.ts
  src/services/test.service.ts
  src/types/express.d.ts
  tsconfig.json
Labels: ✨ Feature

#21 [Feat]#20 - UpdateColumn 수정, token types 추가
  src/controllers/companyNotice/companyNotice.controller.ts
  src/entities/DateEntity.ts
  src/middlewares/auth.middlewares.ts
  src/services/companyNotice/companyNotice.service.ts
  src/types/express.d.ts
Labels: ✨ Feature

#22 [Feat]#20 - 출퇴근 등록
  src/config/data-source.ts
  src/controllers/index.ts
  src/controllers/timelog/timelog.controller.ts
  src/entities/TimeLog.ts
  src/modules/timestamp.ts
  src/routes/index.ts
  src/routes/timelog/timelog.route.ts
  src/services/timelog/timelog.service.ts
Labels: ✨ Feature

#23 [Feat] #17 - 채팅방 목록 조회기능 구현
  .gitignore
  package-lock.json
  package.json
  src/controllers/companyChatroom/companyChatroom.controller.ts
  src/routes/companyChatroom/companyChatroom.route.ts
  src/routes/index.ts
  src/services/companyChatroom/companyChatroom.service.ts
Labels: ✨ Feature

#24 [Feat] #18 - 채팅방 생성 기능 구현
  src/controllers/companyChatRoom/companyChatRoom.controller.ts
  src/entities/CompanyChatRoom.ts
  src/entities/UserCompanyChat.ts
  src/interfaces/companyChat/createChatRoom.dto.ts
  src/modules/jwt.ts
  src/routes/companyChatRoom/companyChatRoom.route.ts
  src/routes/index.ts
  src/services/companyChatRoom/companyChatRoom.service.ts
Labels: ✨ Feature

#27 [Bug] #26 - 채팅 관련 폴더 통합
  src/controllers/companyChatRoom/companyChatRoom.controller.ts
  src/controllers/companyChatroom/companyChatroom.controller.ts
  src/routes/companyChatRoom/companyChatRoom.route.ts
  src/routes/companyChatroom/companyChatroom.route.ts
  src/services/companyChatRoom/companyChatRoom.service.ts
  src/services/companyChatroom/companyChatroom.service.ts
Labels: 🐞 BugFix

#30 [Feat]#25 - 출퇴근 조회
  package-lock.json
  package.json
  src/controllers/timelog/timelog.controller.ts
  src/entities/TimeLog.ts
  src/modules/timestamp.ts
  src/routes/timelog/timelog.route.ts
  src/services/timelog/timelog.service.ts
Labels: ✨ Feature

#31 [Feat] #10 - 회원정보 수정, 회원탈퇴 서비스, 회원정보 상세 조회 구현
  package-lock.json
  package.json
  src/controllers/user/user.controller.ts
  src/interfaces/common/user/userDto.ts
  src/interfaces/user/user.dto.ts
  src/middlewares/auth.middlewares.ts
  src/routes/user/user.route.ts
  src/services/user/user.service.ts
Labels: ✨ Feature

#32 [Feat] #28 - 채팅 기능 구현
  package-lock.json
  src/index.ts
  src/interfaces/socket/socket.dto.ts
  src/socket.ts
Labels: ✨ Feature
